<?php
$this->headTitle()->setSeparator(' - ')
                  ->setDefaultAttachOrder('PREPEND')
                  ->setAutoEscape(false);
$this->headTitle('PHP-UserGroup');

$basePath = $this->basePath();
$this->headLink()->appendStylesheet($basePath . '/lib/bootstrap/css/bootstrap.min.css')
                 ->appendStylesheet($basePath . '/css/phpug/style.css')
                 ->appendStylesheet($basePath . '/lib/font-awesome/css/font-awesome.min.css')
              //   ->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css')
;

$this->headLink(array(
            'rel'  => 'shortcut icon',
         //   'type' => 'image/vnd.microsoft.icon',
            'type' => 'image/png',
            'href' => $basePath . '/img/phpug/favicon.png',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript',
    array('conditional' => 'lt IE9',));

$this->headScript()->prependFile($basePath . '/lib/bootstrap/js/bootstrap.min.js');
$this->headScript()->prependFile($basePath . '/js/jquery.cookie.js');
$this->headScript()->prependFile($basePath . '/lib/jquery/jquery-migrate-1.2.1.min.js');
$this->headScript()->prependFile($basePath . '/lib/jquery/jquery.js');
$this->headScript()->appendScript('//<![CDATA[
var pkBaseURL = (("https:" == document.location.protocol) ? "https://piwik.heigl.org/" : "http://piwik.heigl.org/");
document.write(unescape("%3Cscript src=\'" + pkBaseURL + "piwik.js\' type=\'text/javascript\'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
    var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);
    piwikTracker.trackPageView();
    piwikTracker.enableLinkTracking();
} catch( err ) {}

$(".navigation").contents().filter(function(){return this.nodeType === 3;}).remove();
//]]>');
echo $this->doctype();
?><html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle()->toString() ?>
    <?php echo $this->headMeta() ?>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <?php echo $this->headLink() ?>
  </head>

  <body>
    <header class="navbar navbar-inverse navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">PHP.UserGroup</a></h1>
        </div>
        <div class="collapse navbar-collapse bs-navbar-collapse">
            <?php echo $this->navigation('navigation')->menu('navigation')->setUlClass('nav navbar-nav'); ?>
            <ul class="nav navbar-nav navbar-right navbar-login">
                <li>
                    <?php echo $this->hybridauthinfo(); ?>
                </li>
            </ul>
        </div>
    </header>
    <section class="container content">
        <div class="row">
            <div class="span12">
                <?php echo $this->content; ?>
            </div>
        </div>
    </section>
    <footer class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
        <div class="navbar-header">
        <small>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bottom-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse bottom-collapse">
                <span class="pull-left navbar-text">© 2011-<?php echo date('Y');?> by</span>
            <?php echo $this->navigation('footer')->menu('footer')->setUlClass('nav navbar-nav'); ?>
            </div>
        </small>
        </div>
    </footer>
    <a href="http://github.com/php-ug/php.ug" class="fork-on-github">
    	<img src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png" alt="Fork me on GitHub">
    </a>
        <!-- Scripts -->
    <?php echo $this->headScript() ?>
  </body>
</html>