<?php
$this->headTitle('About');
?>
<section id="about">
    <h3>PHP.ug</h3>
    <h4>An international meeting-point for the PHP-Community</h4>
    <dl>
    <dt>What is it</dt>
    <dd>
    <p>This website provides you with a possibility to see which Usergroups are
    available in your area as well as contact-informations for each of these usergroups.
    </p>
    </dd>
    <dt>Who is displayed?</dt>
    <dd><p>Every PHP-Usergroup worldwide <a href="<?php echo $this->url('ug/team');
    ?>">we</a> know about.</p>
    <p>If <strong>you</strong> know of a PHP-Usergroup that is not listed, then please extend
     our knowledge by <!-- either using the enrollment form or by --><a href="<?php
     echo $this->url('contact');?>">providing us</a> with some informations
     about that Usergroup. Please provide at least
     a short name, a location, a website and  some contact-information like
      email-address, IM-Infos or twitter-nick.</p>
    </dd>
    <dt>Who benefits from it?</dt><dd>
    <p>Clearly you, as you can check which Usergroup is near you!</p></dd>
    <dt>Who pays for it?</dt><dd>
    <p>Simple Question, simple answer - No one pays for it.</p><p> Well, obviously
    someone has to pay for hosting etc, but thats our own private fun. There is
    no company involved behind the scenes and no sponsorship that would benefit
    from this WebSite.</p></dd>
    <dt id="access">Access</dt><dd>
            Access to the group and its informations should be free for everyone.
            <p>That
            we do not want to pay for informations about a certain usergroup
            seems to be obvious. But do you want to register for a certain
            service just to find out whether a group is meeting today or not?
            And not everyone is on Facebook, Goolge+, JoindIn or Xing (just to
            name a few). So please keep the basic informations about your group
            freely accessible.</p>
            <p>That also means that no one should need to pay for attendance
            of a usergroup-Meeting. Of course costs need to be covered, but
                you'd better try to find a sponsor for covering the costs.
            Otherwise it seems more like a conference, doesn't it?</p>
    </dd>
    </dl>
</section>

<!--
======
php.ug
======

An international meeting-point for the PHP-Community.

-------
Purpose
-------

This Website provides a location for PHP usergroups worldwide to advertise
their existence, their meetings and their contact-details.

For that we include a map on the frontpage that displays every registered
location worldwide. The User can then select the nearest UG and see the
relevant informations like next meeting and contact-informations

From their you can jump to their website immediately

Also a shortlink is provided for every UG so their website can be reached
using an UTL like http://php.ug/ffm for the Usergroup at Frankfurt/Main in
Germany or http://php.ug/benelux for the UG in the Benelux-Countries.

For that every Usergroup can register by providing a unique identifier
(ffm or benelux), a website and some contact-informations (mainly email,
but twitter, facebook or Chat are also possible) and a location where (or
around where) the meetings are held.

The provided email-address will then get the login information to change and
maintain the provided data.

All Usergroups will have to verify their existence at least once a year so we
can archive inactive groups.

The meeting schedule will be retrieved weekly from an iCalendar-File the
usergroup should provide on their Website. That makes it easier to maintain
a consistent Dataset of the schedules as the UG only needs to maintain their
local calendar and this website will retrieve that information. If no URL to
that calendar is given, then no meeting-schedule will be displayed.

NO statistics will be provided.

-----
Costs
-----

The registering usergroups will not have to pay for this service!

But - of course - donations to pay the bills are always welcome.

Also help by coding the stuff behind is highly appreciated!

 -->