<?php
$this->headTitle('About');
?>
<section id="about">
    <h3>PHP.ug</h3>
    <h4>An international meeting-point for the PHP-Community</h4>
    <dl>
        <dt>What is it</dt>
        <dd>
            <p>This website provides you with a possibility to see which Usergroups are
            available in your area as well as contact-informations for each of these usergroups.
            </p>
        </dd>
        <dt>Who is displayed?</dt>
        <dd>
            <p>Every PHP-Usergroup worldwide <a href="<?php echo $this->url('ug/team');
            ?>">we</a> know about.</p>
            <p>If <strong>you</strong> know of a PHP-Usergroup that is not listed, then please extend
            our knowledge by either using the <a href="<?php echo
                $this->url('ug/promote'); ?>">promotion-form</a>a> or by <a href="<?php
            echo $this->url('contact');?>">providing us</a> with some informations
            about that Usergroup. Please provide at least
            a short name, a location, a website and  some contact-information like
            email-address, IM-Infos or twitter-nick.</p>
        </dd>
        <dt>Who benefits from it?</dt>
        <dd>
            <p>Clearly you, as you can check which Usergroup is near you!</p>
        </dd>
        <dt>Who uses it?</dt>
        <dd>The Whole PHP-Community. The data is available via an API which is
            already being used to show the list of usergroups on the
            <a href="http://www.php.net/ug.php">PHP.net</a>-Website
        </dd>
        <dt>Who pays for it?</dt>
        <dd>
            <p>Simple Question, simple answer - No one pays for it.</p><p> Well, obviously
            someone has to pay for hosting etc, but that's our own private fun. There is
            no company involved behind the scenes and no sponsorship that would benefit
            from this WebSite. If you want to help us out with the bills feel free to <a href="<?php
            echo $this->url('contact');?>">contact us</a></p>
        </dd>
        <dt id="access">Access</dt>
        <dd>
            Access to the group and its informations should be free for everyone.
            <p>That
            we do not want to pay for informations about a certain usergroup
            seems to be obvious. But do you want to register for a certain
            service just to find out whether a group is meeting today or not?
            And not everyone is on Facebook, Goolge+, JoindIn or Xing (just to
            name a few). So please keep the basic informations about your group
            freely accessible.</p>
            <p>That also means that no one should need to pay for attendance
            of a usergroup-Meeting. Of course costs need to be covered, but
                you'd better try to find a sponsor for covering the costs.
            Otherwise it seems more like a conference, doesn't it?</p>
        </dd>
    </dl>
</section>
