<?php
$this->headTitle('One home for one community');
$this->headLink()->appendStylesheet('lib/leaflet/leaflet.css');
$this->headLink()->appendStylesheet('lib/leaflet/leaflet.css','text/css',
    array('conditional' => 'lte IE8',)
);
$this->headLink()->appendStylesheet('lib/leafletsearch/css/l.geosearch.css');

$this->headScript()->prependFile('js/phpug.js');
$this->headScript()->prependFile('lib/leafletsearch/js/l.geosearch.provider.openstreetmap.js');
$this->headScript()->prependFile('lib/leafletsearch/js/l.control.geosearch.js');
$this->headScript()->prependFile('lib/leaflet-layerjson/leaflet-layerjson.src.js');
$this->headScript()->prependFile('lib/overlappingMarkerSpiderfier/oms.min.js');
$this->headScript()->prependFile('lib/leaflet/leaflet.js');
?>
<div id="map"></div>
<?php if(count($flash)) : ?>
<div class="alert alert-success alert-dismissable" style="position:absolute; list-style-type: none">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <ul style="list-style-type:none;">
        <?php foreach ($flash as $msg) : ?>
            <li><?php echo $msg; ?></li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>