<?php
$this->headTitle('Legal');

$this->headScript()->appendScript("// <![CDATA[
    $('#toggletrackingstate').click(function(e){
        e.preventDefault();
        if($('#trackingstate').is(':visible')){
            $('#trackingstate').hide(2000);
        } else {
            $('#trackingstate').show(2000);
        }
        return false;
    });
$('#trackingstate').hide();
// ]]>");
?>
<div id="legal" xmlns="http://www.w3.org/1999/html">
<h3>Legal stuff</h3>
<h4>User Tracking</h4>
<p>Users are tracked using <a href="http://piwik.org">piwik</a>, a free website-tracking tool.</p>
<p>
    Your IP-Address will only be logged with the first two segments.
    So regardless what your IP-Address is, it will always look like x.y.0.0 to our tracking system.
</p>
<p>
    <a id="toggletrackingstate" target="_blank" href="#">
        Here you can see your current tracking-status:
    </a>
    <iframe id="trackingstate" style="display:block;margin:10px 5% 10px 5%;border:1px solid gray;" frameborder="no" width="90%"src="http://piwik.heigl.org/index.php?module=CoreAdminHome&action=optOut&language=en"></iframe>
</p>
<h4>Terms of Service</h4>
<ul>
<li>Usage of this Site is free</li>
<li>If you want to handle your usergroups data yourself, you need at least one
Twitter-Account. This Twitter-account will be used for:<dl><dt>Login</dt>
<dd>Each user login into this page with a user-account associateds with a 
usergroup can edit the information for that usergroup</dd>
<!--<dt>Messaging</dt><dd>On associating a Twitter-Account with a usergroup the
PHP-UG-Tweetbot will start following that useraccount. All Tweets from that 
useraccount will then be displayed at this page.</dd>-->
    </dl>
</li>
<li>Data you have entered on this site will be made available to the public via an API.</li>
    <li>There is no warranty whatsoever for anything when using this site.
        We do our best to keep it up and up-to-date but we can not take any legal
        responsibility. THE ENTIRE RISK IS WITH YOU.</li>
</ul>
</div>