<?php
$this->headTitle('Legal');
?>
<div id="legal">
<h3>Legal stuff</h3>
<h4>Terms of Service</h4>
<ul>
<li>Usage of this Site is free</li>
<li>If you want to handle your usergroups data yourself, you need at least one
Twitter-Account. This Twitter-account will be used for:<dl><dt>Login</dt>
<dd>Each user login into this page with a user-account associateds with a 
usergroup can edit the information for that usergroup</dd>
<dt>Messaging</dt><dd>On associating a Twitter-Account with a usergroup the 
PHP-UG-Tweetbot will start following that useraccount. All Tweets from that 
useraccount will then be displayed at this page.</dd></dl>
</li>
    
</ul>
</div>