<?php
$this->headTitle('Team');
$this->headLink()->appendStylesheet($this->basePath() . '/css/phpug/phpugteam.css');
?>
<div id="team">
    <h3><?php echo $this->translate('The team behind PHP.ug');?></h3>
    <dl>
    <?php foreach ( $this->team as $mail => $person ) : ?>
        <dt><?php echo $this->gravatar(trim($mail), array('img_size'=>'100'))?></dt>
        <dd>
            <h3><?php echo $person['name']; ?></h3>
            <?php echo $this->mailto($mail, null, array('title' => 'Send Email to ' . $person['name']))?>
            <?php if ( isset($person['twitter']) ) :?>
            <a title="Go to the Twitter-account of <?php echo $person['name']; ?>" href="http://twitter.com/!#<?php echo $person['twitter']; ?>">
                <i class="fa fa-twitter fa-2x"></i>
            </a>
            <?php endif; ?>
            <?php if ( isset($person['google+']) ) :?>
                <a title="Go to the google+-account of <?php echo $person['name']; ?>" href="https://plus.google.com/<?php echo $person['google+']; ?>">
                    <i class="fa fa-google-plus fa-2x"></i>
                </a>
            <?php endif; ?>
            <?php if ( isset($person['github']) ) :?>
                <a title="Go to the github-account of <?php echo $person['name']; ?>" href="https://github.com/<?php echo $person['github']; ?>">
                    <i class="fa fa-github fa-2x"></i>
                </a>
            <?php endif; ?>
        </dd>
    <?php endforeach; ?>
    </dl>
</div>

