<?php
$this->headTitle('Tips & Tricks on running a PHP-Usergroup');
?>
<div id="tips">
    <h3>Tips & Tricks on running a PHP-Usergroup</h3>
    <p>
        You can find a list of links we found helpful for getting a usergroup up and running.
        If you know other links that you think might be helpful please either send us a pull request or a short note
        via the <a href="<?php echo $this->url('contact'); ?>">contact-form</a>.
    </p>
    <h4>General Resources about PHP Usergroups</h4>
    <dl>
        <dt><a href="https://wiki.php.net/usergroups">PHP-Usergroup on PHP.net</a></dt>
        <dd>
            Have a look at the resources PHP.net has to offer. You should think about subscribing to the UD-Admin mailinglist.
        </dd>
        <dt><a href="http://www.phpusergroups.org">PHPUsergroups.org</a></dt>
        <dd>
            Resources about PHP-Usergroups. The list of Usergroups is in some parts a bit outdated.
        </dd>
    </dl>
    <h4>General Resources about Usergroups - <strong>Not PHP-Specific</strong></h4>
    <dl>
        <dt><a href="https://confluence.atlassian.com/display/AUG/AUG+Cookbook">Atlassian Usergroup Cookbook</a></dt>
        <dd>
            Atlassian provides excellent resources for setting up an Atlassian Usergroup. Skip some details and you
            can use it for PHP-Usergroups as well.
        </dd>
        <dt><a href="https://confluence.atlassian.com/download/attachments/116195441/AUGCookbook_Checklist.pdf">
            Atlassian Usergroup Checklist
        </a></dt>
        <dd>
            It's as always: If you can't automate it at least have a checklist at hand! And this one from Atlassian
            comes in quite handy if you do nat already have your own one.
        </dd>
    </dl>
    <h4>Sponsorship and Partnership-Projects</h4>
    <dl>
        <dt>
            <a href="http://www.zend.com/en/community/user-groups-affiliate">Zend Usergroup-Afiliate-Program</a>
        </dt>
        <dd>
            Zend can help you get a commision on purchase made via your website. And on top of that your
            usergroup-members will also get a discount on their purchase.
        </dd>
        <dt>
            <a href="http://blog.jetbrains.com/webide/2012/12/supporting-communities-user-groups-and-open-source-projects/">
                JetBrains sponsorship
            </a>
        </dt>
        <dd>
            JetBrains has announced a sponsorship-program for usergroups as well as conferences or other tech stuff.
        </dd>
        <dt>
            <a href="http://blog.engineyard.com/2012/announcing-our-new-php-user-group-program/">
                Engineyards Usergroup program
            </a>
        </dt>
        <dd>
            Engineyard also set up a usergroup program for PHP-Usergroups. You might even get a sponsorship for one of
            your meetings.
        </dd>
    </dl>
</div>