<?php
$this->headLink()->appendStylesheet($this->basePath . '/lib/fullcalendar/fullcalendar.css');
$this->headLink()->appendStylesheet($this->basePath . '/lib/fullcalendar/fullcalendar.print.css', 'print');
$this->headLink()->appendStylesheet($this->basePath . '/lib/jBox/jBox.css');

$this->headScript()->prependScript("// <![CDATA[
    $(document).ready(function() {

		$('#calendar').fullCalendar({
		    timezone: 'local',
		    timeFormat: 'H:mm',
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},
			defaultDate: new Date(),
			contentHeight: 'auto',
			aspectRatio: 1,
			editable: false,
			eventLimit: true,
			eventSources : [{
				url: '" . $this->url('api/v1', array('controller' => 'calendar', 'action' => 'list'), array('force_canonical' => true)) . "',
				cache : true,
				error: function() {
					alert('Sorry, but the event-server seems to have a problem');
				},
				color: 'rgb(40,128,202)',
				textColor: 'white'
			},{
				events: function(start, end, timezone, mycallback) {
					$.ajax({
            			url: 'http://api.joind.in/v2.1/events?filter=upcoming&verbose=yes&resultsperpage=100&tags[]=php',
            			jsonp: 'callback',
            			dataType: 'jsonp',
            			success: function(doc) {
                			var events = [];
                			for (i=0;i<doc.events.length; i++) {
                				item = doc.events[i];
                    			events.push({
                        			title: item.name,
                        			start: item.start_date,
                        			end: item.end_date,
                        			description: item.description,
                        			url: item.website_uri
			                    });
            			    }
                			mycallback(events);
            			}
        			});
				},
				color: 'rgb(231,131,19)',
				textColor: 'white'
			}/*,{
				events: function(start, end, timezone, mycallback) {
					$.ajax({
            			url: 'http://api.joind.in/v2.1/events?filter=upcoming&verbose=yes&resultsperpage=100&tags[]=php',
            			jsonp: 'callback',
            			dataType: 'jsonp',
            			success: function(doc) {
                			var events = [];
                			for (i=0;i<doc.events.length; i++) {
                				item = doc.events[i];
                				if (!item.cfp_end_date) {
                					continue;
                				}
                    			events.push({
                        			title: '[CfP] ' + item.name,
                        			start: item.cfp_start_date,
                        			end: item.cfp_end_date,
                        			description: item.description,
                        			url: item.website_uri
			                    });
            			    }
                			mycallback(events);
            			}
        			});
				},
				color: 'lightgreen',
				textColor: 'black'
			}*/],
			eventRender: function(event, element){
			    new jBox('Tooltip', {
			        title: event.title,
                    content: event.description,
                    maxWidth: 200,
                    constructOnInit: true,
                    trigger: 'mouseenter',
                    attach: element,
                });
			},
			loading: function(bool) {
				$('#loading').toggle(bool);
			}
		});

	});
// ]]>");
$this->headScript()->prependFile($this->basePath . '/lib/jBox/jBox.min.js');
$this->headScript()->prependFile($this->basePath . '/lib/fullcalendar/fullcalendar.min.js');
$this->headScript()->prependFile($this->basePath . '/lib/moment/moment.min.js');
?>
<div id='calendar'></div>