<?php
$this->headLink()->appendStylesheet($this->basePath . '/css/phpugfeatures.css');
$this->headLink()->appendStylesheet($this->basePath . '/orgheiglgeolocation/lib/leaflet-0.7.3/leaflet.css');
$this->headScript()->appendFile($this->basePath . '/orgheiglgeolocation/lib/leaflet-0.7.3/leaflet.js');
$this->headScript()->appendFile($this->basePath . '/lib/leaflet-search/dist/leaflet-search.min.js');
$this->headScript()->appendFile($this->basePath . '/orgheiglgeolocation/js/orgHeiglGeolocation.js');

$this->headScript()->appendScript("// <![CDATA[

             $('.orgheiglgeolocation').orgHeiglGeolocation();

            function outputUpdate(dist) {
                document.querySelector('#distanceoutput').value = dist;
            }

            function populatelatlon(foo) {
            }

            $('#location').on('change', function(e){
                var input = $(e.target);
                var lll = input.val().match(/([-]?\d{1,2}(\.\d+)?)[^\d\.\-]+([-]?\d{1,3}(\.\d+)?)/);
                if (! lll) {
                    lll = [0,0,0,0,0];
                }
                $('#latitude').val(lll[1]);
                $('#longitude').val(lll[3]);
            });

            function populate() {
                document.querySelector('#location').value = 'foooo';
            }

            $('.addSearch').each(function(item, value){
                value.href = value.href + document.location.search.replace(/\?/, '&');
            });

            $('#showlimitentries').on('click', function(){
                if ($('#locationselector').is(':visible')) {
                    $('#locationselector').hide();
                    $('#showlimitentries').text('Limit to usergroups around a location');
                } else {
                    $('#locationselector').show();
                    $('#showlimitentries').text('Hide options');
                }
            });
            $('#locationselector').hide();
         //  ]]>");

?>
<div class="jumbotron">
    <h3>
        List of Usergroup-Events
    </h3>
    <p>
        The listed usergroups are organising the following events throughout the next year.
    </p>
    <p>
        You can
        <a class="addSearch" href="<?php echo preg_replace('/^https?/', 'webcal', $this->url('api/v1', array('controller' => 'calendar', 'action' => 'list'), array('force_canonical' => true))); ?>?format=ical">subscribe</a>
        to this feed or
        <a class="addSearch" href="<?php echo $this->url('api/v1', array('controller' => 'calendar', 'action' => 'list'), array('force_canonical' => true)); ?>?format=ical">download</a>
        it as iCalendar-File
    </p>
    <p>
    <a id="showlimitentries" class="btn btn-default" href="#">Limit to usergroups around a location</a>
        <a class="btn btn-default" href="<?php echo $this->url('api/v1', array('controller' => 'calendar', 'action' => 'list'), array('force_canonical' => true)); ?>">
            Show Events of <strong>all</strong> Usergroups
        </a>
    <form method="get" id="locationselector" action="<?php echo $this->url('api/v1', array('controller' => 'calendar', 'action' => 'list')); ?>">
        <div class="form-group">
            <label for="location">Location</label>
            <input class="form-control orgheiglgeolocation" value="<?php echo $this->location; ?>" type="text" id="location" name="location"/>
            <div id="location_wrapper">
            <div class="map"></div>
            </div>
            <input type="hidden" value="<?php echo $this->latitude; ?>" name="latitude" id="latitude"/>
            <input type="hidden" value="<?php echo $this->longitude; ?>" name="longitude" id="longitude"/>
        </div>
        <div class="form-group">
            <label for="distance">
                Display Events within <output style="display:inline" for="distance" id="distanceoutput"><?php echo $this->distance; ?></output> km distance
            </label>
            <input class="formcontrol" type="range" min="5" max="500" value="<?php echo $this->distance; ?>" name="distance" id="distance" oninput="outputUpdate(value)">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-default">Limit</button>
        </div>
    </form>
    </p>
</div>
<ul class="event-list" style="column-count: 3; list-style-type:none;">
<?php
$events = $this->calendar->getEvents(new DateInterval('P1Y'));
foreach ($events as $event) : ?><li style="border:1px solid gray; border-radius: 1em;margin:1rem;padding: 1rem;">
    <h4 style="border-radius: 1rem 1rem 0 0; background-color: gray; color: white;margin: -1rem -1rem 1rem -1rem; padding: 1rem">
    <?php $url = $event->getUrl(); if ($url) { ?>
        <a style="color:white;" href="<?php echo $url;?>">
            <?php } ?>
            <?php echo $event->getName(); ?>
        <?php if ($url) : ?>
        </a>
        <?php endif; ?>
    </h4>
    <p class="daterange">
        <?php echo $this->dateRangePrinter($event->getStartDate(), $event->getEndDate(), 'd.m.Y H:i', new DateTimezone('Europe/Berlin')); ?>
    </p>
    <p>
        <?php echo $event->getDescription(); ?>
    </p>
</li><?php endforeach; ?>
</ul>
